// src/as-datagrid.tsx
import { render } from 'solid-js/web'
import { createSignal, For, createMemo } from 'solid-js'
import { createThemeSync } from './theme-sync'

interface Column { key: string; header: string }

class AsDatagrid extends HTMLElement {
  private dispose?: () => void
  private themeCleanup?: () => void
  private _data: any[] = []
  private _columns: Column[] = []
  private _filterTimer?: ReturnType<typeof setTimeout>

  connectedCallback() {
    const [data, setData] = createSignal(this._data)
    const [columns, setColumns] = createSignal(this._columns)
    const [pageSize] = createSignal(parseInt(this.getAttribute('pageSize') || '15'))
    const [title] = createSignal(this.getAttribute('title') || '')
    const [selectable, setSelectable] = createSignal(this.hasAttribute('selectable'))
    const [pageable, setPageable] = createSignal(this.hasAttribute('pageable'))
    const [filterable, setFilterable] = createSignal(this.hasAttribute('filterable'))
    const [actionable, setActionable] = createSignal(this.hasAttribute('actionable'))

    const [rawFilter, setRawFilter] = createSignal('')
    const [filter, setFilter] = createSignal('')
    const [sortKey, setSortKey] = createSignal<string | null>(null)
    const [sortDir, setSortDir] = createSignal(1)
    const [page, setPage] = createSignal(0)
    const [selectedRow, setSelectedRow] = createSignal<any>(null)

    const onFilterInput = (e: Event) => {
      const val = (e.target as HTMLInputElement).value
      setRawFilter(val)
      clearTimeout(this._filterTimer)
      this._filterTimer = setTimeout(() => { setFilter(val); setPage(0) }, 300)
    }

    // NO theme observer - theme is handled by CSS + createThemeSync
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((m) => {
        if (m.type === 'attributes') {
          const a = m.attributeName
          if (a === 'selectable') setSelectable(this.hasAttribute('selectable'))
          if (a === 'pageable') setPageable(this.hasAttribute('pageable'))
          if (a === 'filterable') setFilterable(this.hasAttribute('filterable'))
          if (a === 'actionable') setActionable(this.hasAttribute('actionable'))
        }
      })
    })
    observer.observe(this, { attributes: true })

    const filteredData = createMemo(() => {
      const f = filter().toLowerCase()
      if (!f) return data()
      return data().filter(row => Object.values(row).some(v => String(v).toLowerCase().includes(f)))
    })

    const sortedData = createMemo(() => {
      const d = filteredData()
      const key = sortKey()
      if (!key) return d
      const dir = sortDir()
      return [...d].sort((a, b) => { const av = a[key]; const bv = b[key]; return av < bv ? -dir : av > bv ? dir : 0 })
    })

    const paginatedData = createMemo(() => {
      if (!pageable()) return sortedData()
      const start = page() * pageSize()
      return sortedData().slice(start, start + pageSize())
    })

    const total = createMemo(() => sortedData().length)
    const pages = createMemo(() => Math.ceil(total() / pageSize()))

    const sort = (key: string) => {
      if (sortKey() === key) setSortDir(d => d === 1 ? -1 : 1)
      else { setSortKey(key); setSortDir(1) }
    }

    const selectRow = (row: any) => {
      if (!selectable()) return
      setSelectedRow(row)
      this.dispatchEvent(new CustomEvent('row-select', { detail: { row, id: row?.id }, bubbles: true, composed: true }))
    }

    ;(this as any).updateData = (newData: any[]) => { this._data = newData; setData(newData); setPage(0); setFilter(''); setRawFilter('') }
    ;(this as any).updateColumns = (newColumns: Column[]) => { this._columns = newColumns; setColumns(newColumns) }

    const Component = () => (
      <>
        <style>{`
          :host { display: block; }
          .container {
            border-radius: 0.5rem; overflow: hidden;
            background: #ffffff; color: #3f3f46;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          }
          :host([theme="dark"]) .container {
            background: #27272a; color: #d4d4d8;
          }
          .header { padding: 1rem 1.5rem; display: flex; justify-content: space-between; align-items: center; }
          .title { font-size: 1.25rem; font-weight: 600; }
          .filter-input {
            width: 12rem; padding: 0.375rem 0.625rem; border: 1px solid #d4d4d8;
            border-radius: 0.375rem; font-size: 0.875rem; outline: none;
            background: #ffffff; color: #3f3f46;
            transition: border-color 0.2s; box-shadow: 0 1px 2px 0 rgba(18,18,23,0.05);
          }
          :host([theme="dark"]) .filter-input {
            background: #09090b; color: #ffffff; border-color: #3f3f46;
          }
          :host([theme="dark"]) .filter-input:focus {
            border-color: #3b82f6;
          }
          .filter-input:not(:disabled):focus { border-color: #3b82f6; }
          .table-wrapper { overflow-x: auto; }
          table { width: 100%; border-collapse: collapse; }
          thead {
            background: #f4f4f5; border-bottom: 1px solid #e4e4e7;
          }
          :host([theme="dark"]) thead {
            background: #18181b; border-bottom-color: #3f3f46;
          }
          th {
            padding: 0.5rem 0.25rem; text-align: left; font-size: 0.75rem;
            font-weight: 500; text-transform: uppercase; letter-spacing: 0.05em;
            cursor: pointer; user-select: none; color: #3f3f46;
          }
          :host([theme="dark"]) th { color: #d4d4d8; }
          td {
            padding: 0.5rem 0.25rem; font-size: 0.9375rem;
            border-bottom: 1px solid #e4e4e7;
          }
          :host([theme="dark"]) td { border-bottom-color: #3f3f46; }
          tbody tr:nth-child(even) { background: #f4f4f5; }
          :host([theme="dark"]) tbody tr:nth-child(even) { background: #18181b; }
          tbody tr:hover { background: #eff6ff; }
          :host([theme="dark"]) tbody tr:hover { background: #3f3f46; }
          tbody tr.selectable { cursor: pointer; }
          tbody tr.selected { background: #dbeafe !important; }
          :host([theme="dark"]) tbody tr.selected { background: #1e3a5f !important; }
          td.first-col { border-left: 3px solid transparent; }
          tbody tr.selected td.first-col { border-left-color: #3b82f6; }
          th.action-col, td.action-col { width: 0.5rem; text-align: center; padding: 0; }
          .action-btn {
            background: transparent; border: none; cursor: pointer; font-size: 1.25rem;
            padding: 0 0.25rem; border-radius: 0.25rem; color: #3f3f46;
          }
          :host([theme="dark"]) .action-btn { color: #d4d4d8; }
          .action-btn:hover { background: rgba(0,0,0,0.05); }
          :host([theme="dark"]) .action-btn:hover { background: rgba(255,255,255,0.1); }
          .pagination {
            padding: 0.75rem 0.5rem; border-top: 1px solid #e4e4e7;
            display: flex; justify-content: space-between; align-items: center; font-size: 0.875rem;
          }
          :host([theme="dark"]) .pagination { border-top-color: #3f3f46; }
          .pagination-controls { display: flex; gap: 0.5rem; align-items: center; }
          .page-btn {
            padding: 0.5rem 1rem; border: 1px solid #d4d4d8;
            border-radius: 0.375rem;
            background: #ffffff; color: #3f3f46;
            cursor: pointer; font-family: inherit; font-size: 0.875rem;
          }
          :host([theme="dark"]) .page-btn {
            background: #27272a; color: #d4d4d8; border-color: #3f3f46;
          }
          .page-btn:disabled { opacity: 0.5; cursor: not-allowed; }
          .page-btn:hover:not(:disabled) { background: #f4f4f5; }
          :host([theme="dark"]) .page-btn:hover:not(:disabled) { background: #3f3f46; }
        `}</style>
        <div class="container">
          {(title() || filterable()) && (
            <div class="header">
              <div class="title">{title()}</div>
              {filterable() && (
                <input type="text" class="filter-input" placeholder="Search..." value={rawFilter()} onInput={onFilterInput} />
              )}
            </div>
          )}
          <div class="table-wrapper">
            <table>
              <thead>
                <tr>
                  <For each={columns()}>
                    {(col) => <th onClick={() => sort(col.key)}>{col.header}{sortKey() === col.key ? (sortDir() === 1 ? ' \u2191' : ' \u2193') : ''}</th>}
                  </For>
                  {actionable() && <th class="action-col"></th>}
                </tr>
              </thead>
              <tbody>
                <For each={paginatedData()}>
                  {(row) => (
                    <tr class={`${selectable() ? 'selectable' : ''} ${selectedRow() === row ? 'selected' : ''}`}
                      onClick={() => selectRow(row)}>
                      <For each={columns()}>
                        {(col, idx) => <td class={idx() === 0 ? 'first-col' : ''}>{row[col.key]}</td>}
                      </For>
                      {actionable() && (
                        <td class="action-col">
                          <button class="action-btn" onClick={(e) => {
                            e.stopPropagation()
                            this.dispatchEvent(new CustomEvent('row-action', { detail: { row, id: row?.id, event: e }, bubbles: true, composed: true }))
                          }}>⋮</button>
                        </td>
                      )}
                    </tr>
                  )}
                </For>
              </tbody>
            </table>
          </div>
          {pageable() && (
            <div class="pagination">
              <div># {total()}</div>
              <div class="pagination-controls">
                <button class="page-btn" onClick={() => setPage(page() - 1)} disabled={page() === 0}>&lt;</button>
                <span>{page() + 1} / {pages()}</span>
                <button class="page-btn" onClick={() => setPage(page() + 1)} disabled={page() >= pages() - 1}>&gt;</button>
              </div>
            </div>
          )}
        </div>
      </>
    )

    const shadowRoot = this.attachShadow({ mode: 'open' })
    this.dispose = render(Component, shadowRoot)
    this.themeCleanup = createThemeSync(this)
  }

  disconnectedCallback() { this.dispose?.(); this.themeCleanup?.(); clearTimeout(this._filterTimer) }

  set data(value: any[]) { this._data = value; (this as any).updateData?.(value) }
  get data() { return this._data }
  set columns(value: Column[]) { this._columns = value; (this as any).updateColumns?.(value) }
  get columns() { return this._columns }
  set selectable(value: boolean) { value ? this.setAttribute('selectable', '') : this.removeAttribute('selectable') }
  set filterable(value: boolean) { value ? this.setAttribute('filterable', '') : this.removeAttribute('filterable') }
  set pageable(value: boolean) { value ? this.setAttribute('pageable', '') : this.removeAttribute('pageable') }

  static get observedAttributes() { return ['selectable', 'pageable', 'filterable', 'actionable', 'theme', 'pageSize'] }
}

customElements.define('as-datagrid', AsDatagrid)

// src/components/AsDatagrid.vue
<script setup>
import { ref, computed } from 'vue'

const props = defineProps({
  data: { type: Array, default: () => [] },
  columns: { type: Array, default: () => [] },
  pageSize: { type: Number, default: 15 },
  title: { type: String, default: '' },
  theme: { type: String, default: '' },
  selectable: { type: [Boolean, String], default: false },
  pageable: { type: [Boolean, String], default: false },
  filterable: { type: [Boolean, String], default: false },
  actionable: { type: [Boolean, String], default: false }
})

const isSelectable = computed(() => props.selectable === true || props.selectable === '' || props.selectable === 'true')
const isPageable = computed(() => props.pageable === true || props.pageable === '' || props.pageable === 'true')
const isFilterable = computed(() => props.filterable === true || props.filterable === '' || props.filterable === 'true')
const isActionable = computed(() => props.actionable === true || props.actionable === '' || props.actionable === 'true')

const emit = defineEmits(['row-select', 'row-action'])

const sampleData = Array.from({length: 57}, (_, i) => ({
  id: i + 1,
  name: `Usuario ${i + 1}`,
  email: `user${i + 1}@ejemplo.com`,
  role: ['Admin', 'Editor', 'Viewer'][Math.floor(Math.random()*3)],
  status: Math.random() > 0.5 ? 'Activo' : 'Inactivo'
}))

const sampleColumns = [
  { key: 'name', header: 'Nombre' },
  { key: 'email', header: 'Correo' },
  { key: 'role', header: 'Rol' },
  { key: 'status', header: 'Estado' }
]

const tableData = computed(() => props.data.length > 0 ? props.data : sampleData)
const tableColumns = computed(() => props.columns.length > 0 ? props.columns : sampleColumns)

const filter = ref('')
const sortKey = ref(null)
const sortDir = ref(1)
const page = ref(0)
const selectedRowId = ref(null)

const filteredData = computed(() => {
  if (!filter.value) return tableData.value
  const f = filter.value.toLowerCase()
  return tableData.value.filter(row => 
    Object.values(row).some(v => String(v).toLowerCase().includes(f))
  )
})

const sortedData = computed(() => {
  if (!sortKey.value) return filteredData.value
  return [...filteredData.value].sort((a, b) => {
    const av = a[sortKey.value]
    const bv = b[sortKey.value]
    return av < bv ? -sortDir.value : av > bv ? sortDir.value : 0
  })
})

const paginatedData = computed(() => {
  if (!isPageable.value) return sortedData.value
  const start = page.value * props.pageSize
  return sortedData.value.slice(start, start + props.pageSize)
})

const totalPages = computed(() => Math.ceil(sortedData.value.length / props.pageSize))

function sort(key) {
  if (sortKey.value === key) {
    sortDir.value = sortDir.value === 1 ? -1 : 1
  } else {
    sortKey.value = key
    sortDir.value = 1
  }
}

function selectRow(row) {
  if (!isSelectable.value) return
  selectedRowId.value = row.id
  emit('row-select', { row, id: row.id })
}

function handleAction(row, event) {
  if (isSelectable.value) {
    selectedRowId.value = row.id
  }
  emit('row-action', { row, id: row.id, event })
}
</script>

<template>
  <div 
    v-if="tableData.length && tableColumns.length" 
    class="rounded-lg shadow overflow-hidden"
    :class="theme === 'dark' ? 'bg-gray-800 text-gray-100' : 'bg-white text-gray-800'"
  >
    <div v-if="title || isFilterable" class="pt-[0.4rem] px-2 pb-4 px-6 flex justify-between items-center flex-col md:flex-row gap-2">
      <div v-if="title" class="text-xl font-semibold">{{ title }}</div>
      <div v-else></div>
      <input
        v-if="isFilterable"
        type="text"
        placeholder="🔍" 
        :value="filter"
        @input="e => { filter = e.target.value; page = 0 }"
        class="w-48 px-2.5 py-1.5 border border-surface-300 dark:border-surface-700 rounded text-base outline-none transition-colors duration-200 bg-surface-0 dark:bg-surface-950 text-surface-700 dark:text-surface-0 placeholder:text-surface-500 dark:placeholder:text-surface-400 hover:border-surface-400 dark:hover:border-surface-600 focus:border-primary shadow-[0_1px_2px_0_rgba(18,18,23,0.05)]"
      />
    </div>

    <div class="overflow-x-auto">
      <table class="w-full">
        <thead :class="theme === 'dark' ? 'bg-gray-900' : 'bg-gray-50'">
          <tr class="border-b" :class="theme === 'dark' ? 'border-gray-700' : 'border-gray-200'">
            <th 
              v-for="col in tableColumns" 
              :key="col.key" 
              @click="sort(col.key)"
              class="px-1 py-2 text-left text-xs font-medium uppercase tracking-wide cursor-pointer select-none opacity-70"
              style="padding: 0.5rem 0.25rem;"
            >
              {{ col.header }}
              {{ sortKey === col.key ? (sortDir === 1 ? ' ↑' : ' ↓') : '' }}
            </th>
            <th v-if="isActionable" class="w-2 text-center py-2 px-0"></th>
          </tr>
        </thead>
        <tbody>
          <tr 
            v-for="row in paginatedData" 
            :key="row.id"
            @click="selectRow(row)"
            :class="[
              isSelectable && 'cursor-pointer',
              selectedRowId === row.id && (theme === 'dark' ? 'bg-blue-800' : 'bg-blue-100'),
              selectedRowId !== row.id && (theme === 'dark' ? 'even:bg-gray-900 hover:bg-gray-700' : 'even:bg-gray-50 hover:bg-blue-50')
            ]"
          >
            <td 
              v-for="(col, idx) in tableColumns" 
              :key="col.key"
              :class="[
                'border-b',
                theme === 'dark' ? 'border-gray-700' : 'border-gray-200',
                idx === 0 && 'border-l-[3px]',
                idx === 0 && selectedRowId === row.id ? 'border-l-blue-500' : idx === 0 && 'border-l-transparent'
              ]"
              style="padding: 0.5rem 0.25rem; font-size: 0.9375rem;"
            >
              {{ row[col.key] }}
            </td>
            <td v-if="isActionable" class="w-2 text-center py-0 px-0">
              <button 
                @click.stop="handleAction(row, $event)"
                class="text-xl leading-none p-0 border-none bg-transparent cursor-pointer rounded"
                :class="theme === 'dark' ? 'text-gray-100 hover:bg-gray-600' : 'text-gray-800 hover:bg-gray-200'"
              >
                ⋮
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div v-if="isPageable" class="pt-[0.6rem] px-2 pb-2 border-t flex justify-between items-center text-sm" :class="theme === 'dark' ? 'border-gray-700' : 'border-gray-200'">
      <div># {{ sortedData.length }}</div>
      <div class="flex gap-2 items-center">
        <button 
          @click="page--" 
          :disabled="page === 0"
          class="px-4 py-2 border rounded cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          :class="theme === 'dark' 
            ? 'bg-gray-700 border-gray-600 hover:bg-gray-600' 
            : 'bg-white border-gray-400 hover:bg-gray-100'"
        >
          &lt;
        </button>
        <span>{{ page + 1 }} / {{ totalPages }}</span>
        <button 
          @click="page++" 
          :disabled="page >= totalPages - 1"
          class="px-4 py-2 border rounded cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          :class="theme === 'dark' 
            ? 'bg-gray-700 border-gray-600 hover:bg-gray-600' 
            : 'bg-white border-gray-400 hover:bg-gray-100'"
        >
          &gt;
        </button>
      </div>
    </div>
  </div>
</template>
