// src/components/AsVideo.vue
<script setup>
import { ref, onMounted } from 'vue'

const props = defineProps({
  url: { type: String, default: '' }
})

const width = ref(560)
const height = ref(315)

onMounted(() => {
  if (window.innerWidth < 560) {
    width.value = 310
    height.value = 175
  }
})
</script>

<template>
  <div class="grid place-items-center w-full min-w-80">
    <iframe
      :width="width"
      :height="height"
      frameborder="0"
      :src="url"
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    ></iframe>
  </div>
</template>

// src/as-video.tsx
import { render } from 'solid-js/web'
import { createSignal } from 'solid-js'

class AsVideo extends HTMLElement {
  private dispose?: () => void
  private _observer?: MutationObserver

  connectedCallback() {
    const [width, setWidth] = createSignal(parseInt(this.getAttribute('width') || '560'))
    const [height, setHeight] = createSignal(parseInt(this.getAttribute('height') || '315'))
    const [url] = createSignal(this.getAttribute('url') || '')

    const handleResize = () => {
      if (window.innerWidth < 560) { setWidth(310); setHeight(175) }
      else { setWidth(parseInt(this.getAttribute('width') || '560')); setHeight(parseInt(this.getAttribute('height') || '315')) }
    }

    window.addEventListener('resize', handleResize)

    this._observer = new MutationObserver(() => handleResize())
    this._observer.observe(this, { attributes: true, attributeFilter: ['width', 'height'] })

    const Component = () => (
      <>
        <style>{`
          .video { display: grid; grid-template-areas: stack; place-items: center; width: max(320px, 100%); }
        `}</style>
        <div class="video">
          <iframe
            width={width()} height={height()} frameborder="0" src={url()}
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
          />
        </div>
      </>
    )

    const shadowRoot = this.attachShadow({ mode: 'open' })
    this.dispose = render(Component, shadowRoot)
  }

  disconnectedCallback() { this.dispose?.(); this._observer?.disconnect() }
  static get observedAttributes() { return ['width', 'height', 'url'] }
}

customElements.define('as-video', AsVideo)
